--- #YAML:1.0
name:                CGI-Session-Driver-redis
version:             0.3
abstract:            Persistent session data in CGI applications
license:             ~
author:
    - Steve Kemp <steve@steve.org.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:
    Net::DNS:
    Test::More:
resources:
  bugtracker: https://github.com/skx/Test-RemoteServer/issues
  homepage: https://github.com/skx/Test-RemoteServer/
  repository: https://github.com/skx/Test-RemoteServer.git
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
